### ISSUE TITLE
Could not consult chapter 4 in the book.

### ISSUE THREAD

**Issue by densefog** [DrCuriousVII/PointPleasant#1]
I've unlocked the Book of Phantasm and see the 5 chapters available in the table of contents. I'm able to read them all except for chapter 4. I've tried `Consult IV` and `Consult Runes` which both seem to pull up chapter 3 instead of chapter 4. 

Just a side note, I'm not sure how to re-open the book once I've unlocked it. If I didn't recall how to Consult the book I don't see the table of contents again by doing things like `look book` or `read book`?

**Comment by jasonroelofs** [comment]
Or, possibly, Chapter 4 is getting output along with Chapter 3.

**Comment by DrCuriousVII** [comment]
The bug where attempting to consult chapter 4 returns the text of chapter 3 has been fixed (the commands that should have allowed the player to view IV instead were understood as synonyms for those that viewed III).
