### ISSUE TITLE
Alias suggestions

### ISSUE THREAD

**Issue by jasonroelofs** [DrCuriousVII/PointPleasant#2]
There are some situations where it could help to have some aliases. For example:

`examine tv` as an alias for `examine television`
`take potted plant` or `take plant` could work for `take potted plants`

Along those lines I saw some minor oddities in inventory text related to plural/singular names:

```
You are carrying:
- a potted plants
```

**Comment by DrCuriousVII** [comment]
Some aliases for items have been added, and several items that should have been fixed in place can now no longer be taken by the player.
